version: '3'
services: 
  nginx: 
    build:
      dockerfile: ./docker/nginx-books.dockerfile
      context: .
    image: marcosaraujo/nginx-books
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - production-network
    depends_on: 
      - "node1"
      - "node2"
      - "node3"

  mongodb:
    image: mongo
    container_name: mongo
    networks: 
      - production-network
  
  node1:
    build:
      dockerfile: ./docker/node-books.dockerfile
      context: .
    image: marcosaraujo/node-books
    container_name: node-books-1
    ports:
      - "3000"
    networks:
      - production-network
    depends_on: 
      - "mongodb"

  node2:
    build:
      dockerfile: ./docker/node-books.dockerfile
      context: .
    image: marcosaraujo/node-books
    container_name: node-books-2
    ports:
      - "3000"
    networks:
      - production-network
    depends_on: 
      - "mongodb"

  node3:
    build:
      dockerfile: ./docker/node-books.dockerfile
      context: .
    image: marcosaraujo/node-books
    container_name: node-books-3
    ports:
      - "3000"
    networks:
      - production-network
    depends_on: 
      - "mongodb"

networks:
  production-network:
    driver: bridge
